package Network;

public enum NetworkType {
    USER, CREATE_USER, CREATE_SHIFT, GET_LIST_OF_USERS, GET_SHIFTS_ONE_USER, GET_ALL_SHIFTS, SEND_ALL_SHIFTS, SEND_USERNAME, ERROR
    , GET_ALL_APPLICATIONS, GET_APPLICATION, CREATE_APPLICATION, UPDATE_APPLICATION, DELETE_APPLICATION;
}
